head -c 1KiB /dev/urandom > data/1KiB.txt
head -c 2KiB /dev/urandom > data/2KiB.txt
head -c 3KiB /dev/urandom > data/3KiB.txt
head -c 4KiB /dev/urandom > data/4KiB.txt
head -c 5KiB /dev/urandom > data/5KiB.txt
head -c 6KiB /dev/urandom > data/6KiB.txt
head -c 7KiB /dev/urandom > data/7KiB.txt
head -c 8KiB /dev/urandom > data/8KiB.txt
head -c 9KiB /dev/urandom > data/9KiB.txt
head -c 10KiB /dev/urandom > data/10KiB.txt
